# Generated by Django 5.0.4 on 2024-10-23 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_doc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoDoc', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nroDoc', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('fechaNacimiento', models.DateField()),
                ('carnetLibre', models.CharField(blank=True, max_length=45, null=True)),
                ('carnetNoLibre', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(max_length=45)),
                ('fechaBaja', models.DateTimeField(blank=True, null=True)),
                ('motivoBaja', models.CharField(blank=True, max_length=200, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idTipoDoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='padron.tipo_doc')),
            ],
        ),
    ]
