# Generated by Django 5.0.4 on 2024-11-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_remove_padron_carnetlibre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padron',
            name='nroDoc',
            field=models.IntegerField(unique=True),
        ),
    ]
